### ISSUE TITLE
Upload dll

### ISSUE THREAD

**Issue by steam3d** [SteeBono/airplayreceiver#11]
Can you upload windows compiled dlls? 
I've spent a bunch of hours but still can't compile. I am getting a lot of errors using your instructio
![image_2022-01-06_14-35-10](https://user-images.githubusercontent.com/30986874/148377047-2187762f-82bb-4d5f-bc75-bac8fa9b81b8.png)
n

**Comment by PonyPC** [comment]
use as your own risk
[dll.zip](https://github.com/SteeBono/airplayreceiver/files/7823914/dll.zip)

**Comment by SteeBono** [comment]
Thanks @PonyPC .
I don't currently have a Windows PC 😅
