### ISSUE TITLE
Will this allow 2012 Macbook Air (Catalina) to become AirPlay Reciever (and therefore 2nd monitor) for 2020 Macbook Pro? (Monteray)

### ISSUE THREAD

**Issue by mannyrules** [SteeBono/airplayreceiver#16]
Natively, I can make the Pro the 2nd monitor for the Air, but the Air lacks power and I get laggs and disconnects to the Pro.

Thanks!

Manny

**Comment by SteeBono** [comment]
It is difficult to give an accurate answer, theoretically the receiver developed by apple should be the most reliable and fastest.

They developed the protocol, so the answer is yes, you can use this repo to create a new receiver to use with your macbook air but I don't think it would solve your lag problems.
