### ISSUE TITLE
Mirror iOS 14 on windows

### ISSUE THREAD

**Issue by benchat** [SteeBono/airplayreceiver#2]
Nice Work @SteeBono . Could you outline steps on how to mirror an iPhone?

**Comment by SteeBono** [comment]
Thank you @benchat.

I will try to insert the steps ASAP.

**Comment by SteeBono** [comment]
Hi @benchat,

I have updated the readme and the repo.
Let me know if you can start the project on windows.

**Comment by benchat** [comment]
Hi @SteeBono ,

I was able to follow the instructions as per the updated readme and managed to start the project in Windows successfully. Thank you so much, this is very impressive. Buidling fdk-aac was very seamless. The only issue I encountered was building alac which was throwing some errors.

**Comment by SteeBono** [comment]
Hi @benchat,

You're right, compiling the alac library is a bit more complex.

Glad to have helped you,
S.
