### ISSUE TITLE
why does pts always equal 0?

### ISSUE THREAD

**Issue by yikuo123** [SteeBono/airplayreceiver#21]
OnH264DataReceived: frameType=5, length=5076, pts=0
OnH264DataReceived: frameType=1, length=250, pts=0
OnH264DataReceived: frameType=1, length=384, pts=0
OnH264DataReceived: frameType=1, length=2393, pts=0
OnH264DataReceived: frameType=1, length=3616, pts=0
OnH264DataReceived: frameType=1, length=3747, pts=0

**Comment by SteeBono** [comment]
Unfortunately I don't know, you should do some tests to understand the problem.

I currently don't have time, if you find the solution you can do a PR.

**Comment by SteeBono** [comment]
Yes, you can remove the IF.
