### ISSUE TITLE
How to detect video in portrait or landscape mode

### ISSUE THREAD

**Issue by wenlipeng** [SteeBono/airplayreceiver#22]
The video general in portrait mode.
But when I fullscreen the playing video and rotate the iPhone, the video change to landscape mode.
Currently, how to know the video in landscape mode and need to rotate the decode frame?
Any flag can distinguish this requirement?

**Comment by SteeBono** [comment]
Have you tried to check if it sends you any HTTP request?

**Comment by wenlipeng** [comment]
It works, thank you.
