### ISSUE TITLE
How to play audio data?

### ISSUE THREAD

**Issue by maldin66** [SteeBono/airplayreceiver#27]
Can anyone provide a example of how to play the raw pcm data stream using NAudio or something similar?

**Comment by SteeBono** [comment]
You can try something like that:

    Task _playNAudio;
    BufferedWaveProvider _bufferedWaveProvider;
    
    _airPlayReceiver.OnPCMDataReceived += (s, e) =>
    {
        // PSEUDO CODE
        if(_playNAudio == null)
        {
            _bufferedWaveProvider = new BufferedWaveProvider(new WaveFormat(44100, 16, 2));
            _playNAudio = Task.Factory.StartNew(async () => await PlayAudioExample());
        }

        _bufferedWaveProvider.AddSamples(e.Data, _bufferedWaveProvider.BufferLength, e.Data.Length);
    };
    
    public async Task PlayAudioExample()
    {
        try
        {
            while(_bufferedWaveProvider.BufferedDuration < TimeSpan.FromSecond(5)) 
            {
                await Task.Delay(1000);
            }

            using (var outputDevice = new WaveOutEvent())
            {
                outputDevice.Init(_bufferedWaveProvider);
                outputDevice.Play();
            }
        }
        catch (Exception ex)
        {

        }
    }
