### ISSUE TITLE
Provide license

### ISSUE THREAD

**Issue by vin-fan** [SteeBono/airplayreceiver#29]
Hello, I am referencing your code recently. Could you provide the license of your repository? I found that your repository does not add any license. Thank you.

**Comment by SteeBono** [comment]
Check the repo page, the are a dedicated tab to license:

![image](https://github.com/SteeBono/airplayreceiver/assets/11635557/80876289-777b-405b-b392-e9e0695db254)

I don't take any responsibility for how you'll use the source code you find in my Git repository.
