### ISSUE TITLE
How to view incoming video

### ISSUE THREAD

**Issue by tech234a** [SteeBono/airplayreceiver#3]
I have managed to successfully compile this software and dependencies, and I have been able to connect my device to this software. How would I view the incoming video/audio?

**Comment by SteeBono** [comment]
That project decrypt the video stream in H256 codec and Audio stream in PCM.

You need to develop an additional piece of code to stream the video to VLC for example.

If you search on the internet I think you will already find a library that allows you to send a video / audio stream to an external player.

You can use the '**OnH264DataReceived**' and '**OnPCMDataReceived**' events for the decoded video and audio stream.

Check the '**AirPlayService.cs**' class.

**Comment by tech234a** [comment]
Makes sense, thank you!
