### ISSUE TITLE
Wiki correction in "AirTunes Audio Data Setup"

### ISSUE THREAD

**Issue by fduncanh** [SteeBono/airplayreceiver#6]
Stephano, you have a "cut-and-paste" error  in the Wiki document in the Air Tunes Audio Data Setup response section.

You repeated (by cut-and-paste?) the eventPort/timingPort port response from the first setup request.

After the "streams"  request for type 96, the response should be dataPort/controlPort/96
(like the dataPort/110  "streams" response for type 110).

**Comment by fduncanh** [comment]
Strephano here is the correction for you.


```
<plist version="1.0">
<dict>
        <key>streams</key>
        <array>
                <dict>
                        <key>dataPort</key>
                        <integer>34505</integer>
                        <key>controlPort</key>
                        <integer>40945</integer>
                        <key>type</key>
                        <integer>96</integer>
                </dict>
        </array>
</dict>
</plist>
```
Here (for audio , type 96) you must return the dataPort and controlPort  on your server that you wish the client to use for audio, as well as the type 96.

For video (type 110) only a dataPort (different from the one used by audio) is returned, with type 110.

**Comment by SteeBono** [comment]
Thanks @fduncanh, I fixed the Wiki with your correction.
