### ISSUE TITLE
Instructions for inspecting the dump output?

### ISSUE THREAD

**Issue by michaelforrest** [SteeBono/airplayreceiver#7]
I've got the code running and dumping out screen mirrored frames but I'm not sure how to look at these. 

Can I concatenate these into a file viewable with Quicktime or something? Do I need to create a header?

**Comment by michaelforrest** [comment]
I had missed a socket exception (I was already running AirServer). When I quit AirServer I started to get the dump.h264 file. 
Then I was able to use 
```
ffmpeg -i dump.h264 -c copy output.mp4
```
to take a look at the output.

**Comment by SteeBono** [comment]
Exactly! 

The dump is saved only when you close the application, to carry out the tests.
You can move this logic wherever you want 🔥
