### ISSUE TITLE
Can't run with debug mode

### ISSUE THREAD

**Issue by anatawa12** [SteeBono/airplayreceiver#8]
because DUMP feature is depending on your environment. For me, `/Users/steebono` is not exists.

https://github.com/SteeBono/airplayreceiver/blob/a7634c48c04b170b30dd98a63d7a3cdb72a9509e/AirPlay/Program.cs#L66-L82

Error message:
```
System.UnauthorizedAccessException: Access to the path '/Users/steebono/Desktop/dump/' is denied. ---> System.IO.IOException: Permission denied
```

**Comment by SteeBono** [comment]
You must replace '`/Users/steebono/Desktop/dump/`' in all source codes w/ your path.

If you run on windows: '`C:\Users\Foo\Desktop\dump`' for example.

**Comment by anatawa12** [comment]
Can you change them relative to cwd? I think cwd relative path is a simple way to resolve this problem.

**Comment by SteeBono** [comment]
I can't hard coding paths because Windows uses paths with the backslashes while unix uses forward slashes.

I will insert paths for the dumps in `appsettings.json`.
This way the configuration will depend on the operating system and if you want you can also put path relative to cwd.

**Comment by SteeBono** [comment]
Fixed.

I have added dump path in appsettings.json.

Commit: 98f10d9e01b0685d780813bf720057e552ef992c
