### ISSUE TITLE
Handling video requests

### ISSUE THREAD

**Issue by mynameisvasco** [SteeBono/airplayreceiver#9]
Hello. First of all, let me congratulate your for this amazing work.
I was messing a little bit with this library when I sew that video requests are not handled. 
These requests are sent when you share a video in safari browser using airplay.
Do you have any information about them?

**Comment by SteeBono** [comment]
Hi, I really appreciate it.

I'll check it out.

**Comment by SteeBono** [comment]
I have added 'StreamingListener.cs' as example.

Commit: 43254ae7b331e988b11f9c31de588f3dcdc2dcd6
